repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.3
    hooks:
      - id: ruff-check # Run the linter.
        args: [--fix]
      - id: ruff-format # Run the formatter.
  - repo: https://github.com/astral-sh/uv-pre-commit # uv version.
    rev: 0.8.0
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        types: [python]
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
