[project]
name = "aviation"
version = "0.1.0"
description = "A simple model for global Aviation."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-bibtex>=4.4.0",
]

[dependency-groups]
docs = [
    "mkdocs-bibtex>=4.4.0",
    "mkdocs-material>=9.6.15",
]
